import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

// Color palette
const COLORS = {
  primary: '#1e3a5f',
  accent: '#00b4d8',
  critical: '#dc2626',
  high: '#ea580c',
  moderate: '#d97706',
  low: '#16a34a',
  white: '#ffffff',
  lightGray: '#f1f5f9',
  darkGray: '#475569',
  text: '#1e293b'
};

const DISCLAIMER_TEXT =
  'ACADEMIC DISCLAIMER: This report is generated by an AI-based structural health monitoring system for academic research and demonstration purposes only. ' +
  'The AI predictions, risk scores, anomaly detections, and crack assessments contained herein are preliminary indicators derived from virtual sensor simulation data. ' +
  'These findings do NOT constitute a professional structural engineering assessment and MUST NOT be used as the sole basis for any engineering, safety, or remediation decision. ' +
  'All findings must be verified by a qualified licensed structural engineer through physical inspection, non-destructive testing (NDT), and accepted engineering methodologies.';


/**
 * Generates a professional A4 PDF engineering health report.
 * @param {Object} reportData - Structure, sensor, anomaly, risk, crack, alert data
 * @param {string} outputPath - Absolute file path for the generated PDF
 */
export const generateStructuralReport = (reportData, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50, compress: true });
      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      const {
        structure = {},
        sensorStats = {},
        anomalies = [],
        riskData = {},
        crackData = {},
        alerts = [],
        generatedBy = 'System'
      } = reportData;

      const now = new Date();
      const dateStr = now.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', dateStyle: 'long', timeStyle: 'short' });

      // ===== COVER HEADER =====
      doc.rect(0, 0, doc.page.width, 140).fill(COLORS.primary);
      doc.fillColor(COLORS.white).fontSize(22).font('Helvetica-Bold')
        .text('AI STRUCTURAL HEALTH MONITORING', 50, 28, { align: 'center' });
      doc.fontSize(14).font('Helvetica')
        .text('Engineering Health Assessment Report', 50, 58, { align: 'center' });
      doc.fontSize(10)
        .text(`Generated: ${dateStr}  |  By: ${generatedBy}`, 50, 82, { align: 'center' });

      // Risk badge on header
      const riskLevel = riskData.riskLevel || 'LOW';
      const riskColors = { CRITICAL: '#dc2626', HIGH: '#ea580c', MODERATE: '#d97706', LOW: '#16a34a' };
      const badgeColor = riskColors[riskLevel] || '#16a34a';
      doc.roundedRect(doc.page.width / 2 - 60, 100, 120, 30, 6).fill(badgeColor);
      doc.fillColor(COLORS.white).fontSize(12).font('Helvetica-Bold')
        .text(`RISK: ${riskLevel}`, doc.page.width / 2 - 60, 109, { width: 120, align: 'center' });

      doc.fillColor(COLORS.text).moveDown(5.5);

      // ===== STRUCTURE INFO =====
      sectionHeader(doc, 'STRUCTURE INFORMATION');
      infoRow(doc, 'Structure Name', structure.name || 'N/A');
      infoRow(doc, 'Structure ID', structure.structureId || 'N/A');
      infoRow(doc, 'Type', structure.type || 'N/A');
      infoRow(doc, 'Location', structure.location || 'N/A');
      infoRow(doc, 'Constructed', structure.yearBuilt ? `${structure.yearBuilt}` : 'N/A');
      infoRow(doc, 'Material', structure.material || 'N/A');
      infoRow(doc, 'Report Date', dateStr);
      doc.moveDown(0.8);

      // ===== DISCLAIMER BOX =====
      sectionHeader(doc, 'ACADEMIC DISCLAIMER');
      doc.rect(50, doc.y, doc.page.width - 100, 65).fillAndStroke('#fff3cd', '#d97706');
      doc.fillColor('#92400e').fontSize(8).font('Helvetica')
        .text(DISCLAIMER_TEXT, 58, doc.y + 6, { width: doc.page.width - 116 });
      doc.moveDown(5.5);

      // ===== RISK ASSESSMENT =====
      sectionHeader(doc, 'AI RISK ASSESSMENT SUMMARY');
      infoRow(doc, 'Overall Risk Score', `${riskData.riskScore ?? 'N/A'} / 100`);
      infoRow(doc, 'Risk Classification', riskData.riskLevel || 'N/A');
      if (riskData.mainContributingFactors?.length) {
        infoRow(doc, 'Contributing Factors', riskData.mainContributingFactors.join(', '));
      }
      infoRow(doc, 'AI Recommendation', riskData.recommendation || 'N/A');
      infoRow(doc, 'AI Algorithm', 'Random Forest Regressor (Scikit-learn)');
      doc.moveDown(0.8);

      // ===== SENSOR STATISTICS =====
      sectionHeader(doc, 'SENSOR TELEMETRY SUMMARY');
      const sensorRows = [
        ['Parameter', 'Min', 'Max', 'Avg', 'Unit'],
        ['Vibration', fmt(sensorStats.vibMin), fmt(sensorStats.vibMax), fmt(sensorStats.vibAvg), 'mm/s\u00b2'],
        ['Displacement', fmt(sensorStats.dispMin), fmt(sensorStats.dispMax), fmt(sensorStats.dispAvg), 'mm'],
        ['Strain', fmt(sensorStats.strainMin), fmt(sensorStats.strainMax), fmt(sensorStats.strainAvg), 'ue'],
        ['Temperature', fmt(sensorStats.tempMin), fmt(sensorStats.tempMax), fmt(sensorStats.tempAvg), '\u00b0C'],
        ['Humidity', fmt(sensorStats.humMin), fmt(sensorStats.humMax), fmt(sensorStats.humAvg), '%'],
        ['Crack Width', fmt(sensorStats.crackMin), fmt(sensorStats.crackMax), fmt(sensorStats.crackAvg), 'mm']
      ];
      drawTable(doc, sensorRows);
      doc.moveDown(0.8);

      // ===== ANOMALY LOG =====
      sectionHeader(doc, `ANOMALY DETECTION LOG  (${anomalies.length} events)`);
      if (anomalies.length === 0) {
        doc.fontSize(9).fillColor(COLORS.darkGray).text('No anomalous events recorded in this reporting period.');
      } else {
        const anomalyRows = [['Timestamp', 'Score', 'Parameter', 'Status']];
        anomalies.slice(0, 10).forEach(a => {
          anomalyRows.push([
            a.timestamp ? new Date(a.timestamp || a.createdAt).toLocaleString() : 'N/A',
            fmt(a.score),
            a.affectedParameter || 'N/A',
            a.status || 'Anomalous'
          ]);
        });
        drawTable(doc, anomalyRows);
      }
      doc.moveDown(0.8);

      // ===== CRACK DETECTION =====
      sectionHeader(doc, 'COMPUTER VISION CRACK ANALYSIS');
      if (crackData && crackData.crackDetected !== undefined) {
        infoRow(doc, 'Crack Detected', crackData.crackDetected ? 'YES' : 'NO');
        infoRow(doc, 'Severity', crackData.severity || 'N/A');
        infoRow(doc, 'AI Confidence', crackData.confidence != null ? `${(crackData.confidence * 100).toFixed(1)}%` : 'N/A');
        infoRow(doc, 'Edge Density Ratio', crackData.edgeDensityRatio ?? 'N/A');
        infoRow(doc, 'Recommendation', crackData.recommendation || 'N/A');
        infoRow(doc, 'Algorithm', crackData.algorithm || 'OpenCV CLAHE + Canny + Contour Analysis');
      } else {
        doc.fontSize(9).fillColor(COLORS.darkGray).text('No crack analysis has been performed on this structure.');
      }
      doc.moveDown(0.8);

      // ===== ACTIVE ALERTS =====
      sectionHeader(doc, `SYSTEM ALERT HISTORY  (${alerts.length} alerts)`);
      if (alerts.length === 0) {
        doc.fontSize(9).fillColor(COLORS.darkGray).text('No system alerts recorded.');
      } else {
        const alertRows = [['Alert Type', 'Severity', 'Status', 'Date']];
        alerts.slice(0, 10).forEach(a => {
          alertRows.push([
            a.title || a.type || 'N/A',
            a.severity || 'N/A',
            a.status || 'ACTIVE',
            a.createdAt ? new Date(a.createdAt).toLocaleDateString() : 'N/A'
          ]);
        });
        drawTable(doc, alertRows);
      }
      doc.moveDown(0.8);

      // ===== RECOMMENDATIONS =====
      sectionHeader(doc, 'ENGINEERING RECOMMENDATIONS');
      const recommendations = buildRecommendations(riskData, crackData, alerts, anomalies);
      recommendations.forEach((rec, i) => {
        doc.fontSize(9).fillColor(COLORS.text).font('Helvetica')
          .text(`${i + 1}. ${rec}`, 55, doc.y, { width: doc.page.width - 110 });
        doc.moveDown(0.3);
      });

      // ===== FOOTER =====
      doc.addPage();
      doc.rect(0, 0, doc.page.width, 80).fill(COLORS.primary);
      doc.fillColor(COLORS.white).fontSize(11).font('Helvetica-Bold')
        .text('END OF REPORT', 0, 28, { align: 'center', width: doc.page.width });
      doc.fontSize(8).font('Helvetica')
        .text('This report was auto-generated by the AI Structural Health Monitoring System.', 0, 48, { align: 'center', width: doc.page.width });
      doc.fillColor(COLORS.text).fontSize(8).moveDown(6)
        .text(DISCLAIMER_TEXT, 50, doc.y, { width: doc.page.width - 100, align: 'justify' });

      doc.end();
      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
};


// ===== HELPER FUNCTIONS =====

function sectionHeader(doc, title) {
  doc.rect(50, doc.y, doc.page.width - 100, 20).fill(COLORS.primary);
  doc.fillColor(COLORS.white).fontSize(10).font('Helvetica-Bold')
    .text(title, 58, doc.y - 14, { width: doc.page.width - 116 });
  doc.fillColor(COLORS.text).moveDown(1.2);
}

function infoRow(doc, label, value) {
  const y = doc.y;
  doc.fontSize(9).font('Helvetica-Bold').fillColor(COLORS.darkGray)
    .text(label + ':', 55, y, { width: 160, continued: false });
  doc.fontSize(9).font('Helvetica').fillColor(COLORS.text)
    .text(String(value), 220, y, { width: doc.page.width - 270 });
  doc.moveDown(0.35);
}

function drawTable(doc, rows) {
  const colWidth = (doc.page.width - 100) / (rows[0].length);
  rows.forEach((row, rowIdx) => {
    const y = doc.y;
    if (rowIdx === 0) {
      doc.rect(50, y, doc.page.width - 100, 16).fill(COLORS.lightGray);
    }
    row.forEach((cell, colIdx) => {
      doc.fontSize(rowIdx === 0 ? 8.5 : 8)
        .font(rowIdx === 0 ? 'Helvetica-Bold' : 'Helvetica')
        .fillColor(rowIdx === 0 ? COLORS.primary : COLORS.text)
        .text(String(cell), 52 + colIdx * colWidth, y + 3, { width: colWidth - 6, align: 'left' });
    });
    doc.rect(50, y, doc.page.width - 100, 16).stroke('#cbd5e1');
    doc.moveDown(0.85);
  });
}

function fmt(val) {
  if (val == null) return 'N/A';
  return typeof val === 'number' ? val.toFixed(2) : String(val);
}

function buildRecommendations(riskData, crackData, alerts, anomalies) {
  const recs = [];
  const score = riskData?.riskScore ?? 0;
  const level = riskData?.riskLevel || 'LOW';

  if (level === 'CRITICAL') {
    recs.push('IMMEDIATE ACTION REQUIRED: Engage a licensed structural engineer for on-site inspection within 24 hours.');
    recs.push('Restrict all structural loads and suspend operational activities on this structure until cleared by an engineer.');
  } else if (level === 'HIGH') {
    recs.push('Schedule a comprehensive structural inspection within the next 7 days.');
    recs.push('Increase sensor polling frequency to 30-second intervals and enable real-time threshold alerting.');
  } else if (level === 'MODERATE') {
    recs.push('Conduct a routine structural inspection within 30 days. Review sensor calibration parameters.');
    recs.push('Evaluate epoxy injection for identified micro-crack zones and perform non-destructive testing.');
  } else {
    recs.push('Structure is within acceptable operational parameters. Maintain scheduled quarterly inspection cycle.');
  }

  if (crackData?.severity === 'Critical' || crackData?.severity === 'Severe') {
    recs.push('Crack analysis flagged significant surface deterioration. Deploy acoustic emission (AE) NDT crew for sub-surface analysis.');
  }

  if (anomalies.length > 3) {
    recs.push(`${anomalies.length} anomalous sensor events recorded. Review sensor wiring and structural load history for this period.`);
  }

  const criticalAlerts = alerts.filter(a => a.severity === 'CRITICAL');
  if (criticalAlerts.length > 0) {
    recs.push(`${criticalAlerts.length} CRITICAL alert(s) remain unresolved. Ensure each has been reviewed and actioned by a qualified engineer.`);
  }

  recs.push('All AI findings in this report are preliminary and require validation by a licensed structural engineer through physical inspection.');
  return recs;
}
