import React, { useState } from 'react';
import AcademicDisclaimer from '../components/common/AcademicDisclaimer';
import AlertCard from '../components/dashboard/AlertCard';
import { ShieldAlert, Filter } from 'lucide-react';

export default function Alerts({ alerts = [], onResolveAlert, onAcknowledgeAlert }) {
  const [filterStatus, setFilterStatus] = useState('ALL');

  const filtered = alerts.filter(a => filterStatus === 'ALL' || a.status === filterStatus);

  return (
    <div className="space-y-6">
      <AcademicDisclaimer />

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-slate-100 flex items-center gap-2.5">
            <ShieldAlert className="w-6 h-6 text-rose-500" />
            Automatic Structural Alert Center
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Real-time automated incident triggers generated by Isolation Forest anomalies and threshold violations
          </p>
        </div>

        <div className="flex items-center gap-2 glass-panel p-2 rounded-xl border border-slate-800 text-xs font-mono">
          <Filter className="w-4 h-4 text-cyan-400" />
          <span className="text-slate-400">Status Filter:</span>
          {['ALL', 'ACTIVE', 'ACKNOWLEDGED', 'RESOLVED'].map(st => (
            <button
              key={st}
              onClick={() => setFilterStatus(st)}
              className={`px-2.5 py-1 rounded-md text-[11px] font-semibold transition-colors cursor-pointer ${
                filterStatus === st ? 'bg-cyan-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {st}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filtered.map(alert => (
          <AlertCard
            key={alert.id || alert._id}
            alert={alert}
            onResolve={onResolveAlert}
            onAcknowledge={onAcknowledgeAlert}
          />
        ))}
      </div>
    </div>
  );
}
